In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('magic04.data',header=None)

In [2]:
df.head()

0         1       2       3       4         5        6        7   \
0   28.7967   16.0021  2.6449  0.3918  0.1982   27.7004  22.0110  -8.2027   
1   31.6036   11.7235  2.5185  0.5303  0.3773   26.2722  23.8238  -9.9574   
2  162.0520  136.0310  4.0612  0.0374  0.0187  116.7410 -64.8580 -45.2160   
3   23.8172    9.5728  2.3385  0.6147  0.3922   27.2107  -6.4633  -7.1513   
4   75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277  28.5525  21.8393   

        8         9  10  
0  40.0920   81.8828  g  
1   6.3609  205.2610  g  
2  76.9600  256.7880  g  
3  10.4490  116.7370  g  
4   4.6480  356.4620  g

In [3]:
X = df.drop([10], axis=1)
X = (X-X.mean())/X.std()

Y = df[10]

In [4]:
Y.value_counts() 

g    12332
h     6688
Name: 10, dtype: int64

In [5]:
#pip install imblearn   ## to make the data balanced 

# balancing data

In [6]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(sampling_strategy=1) 
X_res, Y_res = rus.fit_resample(X, Y)   ## balanced 


In [7]:
Y_res.value_counts()

g    6688
h    6688
Name: 10, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score


x_train, x_test, y_train, y_test = train_test_split(X_res,Y_res, test_size=0.30 , shuffle =True)


 # KNeighborsClassifier
  tunning parameters resulted in  n_neighbors =19 

In [9]:
from sklearn.neighbors import KNeighborsClassifier

## cross validation

Best_N_neighbours=1
best_score=0
for i in range (1,50):
    knnclassifier = KNeighborsClassifier(n_neighbors=i)
    score = cross_val_score(knnclassifier,X_res,Y_res, cv=10, scoring ='accuracy').mean() 
    if score > best_score:
        Best_N_neighbours =i 
        best_score = score

In [10]:
knnclassifier = KNeighborsClassifier(n_neighbors=Best_N_neighbours)
knnclassifier.fit(x_train,y_train)
y_pred = knnclassifier.predict(x_test)
metrics.accuracy_score(y_test,y_pred)

0.8155993022676302

In [11]:
metrics.confusion_matrix(y_test,y_pred)

array([[1798,  215],
       [ 525, 1475]], dtype=int64)

In [12]:
report = metrics.classification_report(y_test,y_pred,output_dict=True)
pd.DataFrame(report).transpose()

precision    recall  f1-score      support
g              0.773999  0.893194  0.829336  2013.000000
h              0.872781  0.737500  0.799458  2000.000000
accuracy       0.815599  0.815599  0.815599     0.815599
macro avg      0.823390  0.815347  0.814397  4013.000000
weighted avg   0.823230  0.815599  0.814445  4013.000000

# Decision Tree


In [13]:
from sklearn import tree
dtree =  tree.DecisionTreeClassifier()
dtree.fit(x_train,y_train)
y_pred = dtree.predict(x_test)
metrics.accuracy_score(y_test,y_pred)

0.78320458509843

In [14]:
metrics.confusion_matrix(y_test,y_pred)

array([[1557,  456],
       [ 414, 1586]], dtype=int64)

In [15]:
report = metrics.classification_report(y_test,y_pred,output_dict=True)
pd.DataFrame(report).transpose()

precision    recall  f1-score      support
g              0.789954  0.773472  0.781627  2013.000000
h              0.776690  0.793000  0.784760  2000.000000
accuracy       0.783205  0.783205  0.783205     0.783205
macro avg      0.783322  0.783236  0.783193  4013.000000
weighted avg   0.783343  0.783205  0.783188  4013.000000

# Naive Bias


In [16]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred = gnb.predict(x_test)
metrics.accuracy_score(y_test,y_pred)

0.6501370545726389

In [17]:
metrics.confusion_matrix(y_test,y_pred)

array([[1777,  236],
       [1168,  832]], dtype=int64)

In [18]:
report = metrics.classification_report(y_test,y_pred,output_dict=True)
pd.DataFrame(report).transpose()

precision    recall  f1-score      support
g              0.603396  0.882762  0.716821  2013.000000
h              0.779026  0.416000  0.542373  2000.000000
accuracy       0.650137  0.650137  0.650137     0.650137
macro avg      0.691211  0.649381  0.629597  4013.000000
weighted avg   0.690926  0.650137  0.629880  4013.000000

# Random forest

In [19]:
from sklearn.ensemble import RandomForestClassifier
##
## add cross validation 
##
rf = RandomForestClassifier(n_estimators = 1000)
print(cross_val_score(rf,X_res,Y_res, cv=10, scoring ='accuracy').mean())

0.8640841944741646


In [20]:
#conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
